import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import coverImage from '../../public/homeImages/bikeCover.jpg'
import 'tailwindcss/tailwind.css'
import Main from './components/Main'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Triatleta Pobre',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-Br">
      <body className={inter.className}>
        <div>
          <Main title="Home" backgroundImage={coverImage} imageAlt="" />
          {children}
        </div>
      </body>
    </html>
  )
}
